apiVersion: quay.redhat.com/v1
kind: QuayRegistry
metadata:
  name: quay
spec:
  configBundleSecret: quay-config

  # ensure the ordering of this array is kept or it will break the component patches
  components:
    - kind: quay
      managed: true
    - kind: postgres
      managed: true
    - kind: clair
      managed: true
    - kind: redis
      managed: true
    - kind: horizontalpodautoscaler
      managed: true
    - kind: objectstorage
      managed: true
    - kind: route
      managed: true
    - kind: mirror
      managed: true
    - kind: monitoring
      managed: true
    - kind: tls
      managed: true
    - kind: clairpostgres
      managed: true
