apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: quay-operator
spec:
  name: quay-operator
  channel: __PATCH__
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic
